android.experimental.aarMetadata.strictCheck=false
android.suppressUnsupportedCompileSdk=33
android.useAndroidX=true
android.enableJetifier=true
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.daemon=false
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2
kotlin.daemon.jvm.options=-Xmx1024m,--add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED,--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED,--add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED,--add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED,--add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED,--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED,--add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED,--add-opens=jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED,--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED,--add-opens=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED,--add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED
org.gradle.java.home=/data/data/com.termux/files/usr/lib/jvm/java-17-openjdk
room.skipVerification=true
org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -Dorg.sqlite.lib.path=/data/data/com.termux/files/usr/lib --add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED
